### PR TITLE
Github CI Release Binary

### PR DESCRIPTION
**Pull request by shirshak55**
Here is the initial Github CI.

Currently it releases binary for Apple And Linux GNU

I did tried to setup for windows, windows32 and Linux MUSL (So we can statically compile without requiring glibc etc) but failed miserably due to openssl. And it already took me more than 6-7 hour to setup this ci so may be in future I can check how to support it.

Rust has a great support for rustles so can we use feature flag to compile it?

<3

### CODE REVIEW

**Comment by shirshak55** [comment]
For Initial Testint can u do it from your shell?
```bash
git tag -a v0.1.0 -m "0.1.0"
git push origin v0.1.0
```

**Comment by shirshak55** [comment]
Anyone using binaries should already install postgres and should have openssl installed for linux gnu build because they are dynamically linked. May be we should add it in readme.

**Comment by kooparse** [comment]
Hey, I'll review that shortly (this weekend) ; don't worry! I'll try to merge that asap (and your other PR too)

**Comment by shirshak55** [comment]
@kooparse can you at least tag one release?

**Comment by kooparse** [comment]
Yes, I'm trying everything right now!

**Comment by kooparse** [comment]
Right now, I removed tests for the Rust actions ('cause right now, we need a database for this, so it works on local but not on the CI). I also removed `cargo-diet` for now, I'll check in a more profound way later. The action for creating binaries is running currently.

**Pull request merged**
